spring.application.name=franquicias

# DB
spring.datasource.url=jdbc:postgresql://localhost:5433/franquicias_db
spring.datasource.username=my_user
spring.datasource.password=prueba123*
#prueba123*
spring.jpa.show-sql=true
server.port=8083

springdoc.api-docs.path=/api-docs
